### PR TITLE
Convert use debounce event to ts

### PR DESCRIPTION
**Pull request by ahammadabdullah**
fixes: #2475 
First of all imported the Debounce type definitions and added it accordingly. Added a onClick function because its mandatory in the type definition. 
Run the test and passed all tests. 

- [X] I have read the [Contribution Guide](../packages/core/CONTRIBUTING.md) for this project.

### CODE REVIEW

**Comment by talkor** [comment]
Thanks @ahammadabdullah ! The fix looks great but the branch contains some unrelated commits and Prettier fails, could you please force push with a single commit?

**Comment by ahammadabdullah** [comment]
> Thanks @ahammadabdullah ! The fix looks great but the branch contains some unrelated commits and Prettier fails, could you please force push with a single commit?

yes please give me some time.

**Comment by ahammadabdullah** [comment]
@talkor please check now. Im sorry for the mess. Im not good at advance git yet.

**Review by talkor — APPROVED** [review]
Thank you @ahammadabdullah ! Looks great!

**Pull request merged**
