### PR TITLE
fix: support vitest

### PR DESCRIPTION
**Pull request by talkor**

### CODE REVIEW

**Review by YossiSaadi — APPROVED** [review]
isn't `process.env.NODE_ENV === "test"` also in vitest?

**Comment by talkor** [comment]
> isn't `process.env.NODE_ENV === "test"` also in vitest?

Yes but vitest can't handle `require`

**Comment by YossiSaadi** [comment]
> > isn't `process.env.NODE_ENV === "test"` also in vitest?
> 
> Yes but vitest can't handle `require`

so maybe worth leaving the NODE_ENV one as well

**Comment by YossiSaadi** [comment]
btw its really weird that this code should lay in the component itself, is it really a must in order to do lazy load?

**Comment by talkor** [comment]
> > > isn't `process.env.NODE_ENV === "test"` also in vitest?
> > 
> > 
> > Yes but vitest can't handle `require`
> 
> so maybe worth leaving the NODE_ENV one as well

why? It was for jest because jest isn't very good with esm while vitest is quite the opposite. This check covers both

**Comment by talkor** [comment]
> btw its really weird that this code should lay in the component itself, is it really a must in order to do lazy load?

unfortunately yes, do you have other idea?

**Pull request merged**
