### PR TITLE
docs: migrate dropdown-in-modals stories file to TS

### LINKED ISSUE #2518: docs: convert dropdown-in-modals stories file to TS
Convert the dropdown-in-modals stories file to TypeScript:

- Change the file extension to stories.tsx
- Resolve type issues (if there are), avoid using `any` and prefer existing types

## Related files

`packages/core/src/storybook/patterns/dropdown-in-modals/dropdown-in-modals.stories.js`

---

[Monday ticket [internal]](https://monday.monday.com/boards/3532714909/views/80492480/pulses/7623480229)

### PR DESCRIPTION
**Pull request by blunterdecosta123**
### Changes Made:

- Converted the `dropdown-in-modals` stories file from JavaScript to TypeScript:
  - Changed the file extension to `.storie.tsx`.
  - Resolved type issues and replaced instances of `any` with appropriate TypeScript types.
  - Leveraged existing types from the codebase, ensuring no behavior change in the component's stories.

### Motivation:
The conversion to TypeScript improves type safety and consistency across the codebase. This ensures better maintainability and reduces the likelihood of runtime errors related to improper types.

### Impact:
This change does not affect the functionality or behavior of the component but enhances code clarity and developer experience with better typing.

### Additional Context:
No new dependencies were introduced, and no breaking changes were made to the existing Storybook configuration.

- [x] I have read the [Contribution Guide](../packages/core/CONTRIBUTING.md) for this project.

Resolves #2518

### CODE REVIEW

**Review by rivka-ungar — CHANGES_REQUESTED** [review]
Hey @blunterdecosta123, thanks for your contribution! can you please rename the file to stories.tsx as that is the correct extension for the storybook?

**Comment by rivka-ungar** [comment]
> Hi @rivka-ungar I have successfully renamed the file to stories.tsx via commit [f112a2f](https://github.com/mondaycom/vibe/pull/2529/commits/f112a2feeb976aef524ba6e8a4eb543764ef100a)

Sorry for the confusion, the file should be named the exact same name as the existing file, just the extension should be replaced. So it should be dropdown-in-modals.stories.tsx

**Comment by blunterdecosta123** [comment]
I think now the issue should be solved please review

**Comment by blunterdecosta123** [comment]
> > I think now the issue should be solved please review
> 
> Great job! Could you please run Prettier on your file to ensure consistent formatting?

[2b9b1d2](https://github.com/mondaycom/vibe/pull/2529/commits/2b9b1d2142d47c1e13fda446808b359ddb68ab7e)

**Comment by rivka-ungar** [comment]
> > > I think now the issue should be solved please review
> > 
> > 
> > Great job! Could you please run Prettier on your file to ensure consistent formatting?
> 
> [2b9b1d2](https://github.com/mondaycom/vibe/pull/2529/commits/2b9b1d2142d47c1e13fda446808b359ddb68ab7e)

Can you please run it again? the lint is failing.

**Review by rivka-ungar — APPROVED** [review]
@blunterdecosta123 Great work! thank you for your contribution to vibe!

**Pull request merged**
