### PR TITLE
feat(primary-surface-color): new color token

### PR DESCRIPTION
**Pull request by YossiSaadi**
https://monday.monday.com/boards/3532714909/pulses/7049521708

### CODE REVIEW

**Comment by YossiSaadi** [comment]
@talkor can you please make sure everything is correct here?

**Review by talkor — APPROVED** [review]
Looks good

**Comment by talkor** [comment]
@YossiSaadi you should also add it to the documentation stories in the core package

**Comment by YossiSaadi** [comment]
@talkor mind taking a look again?

**Comment by YossiSaadi** [comment]
> @talkor mind taking a look again?

image

**Review by talkor — APPROVED** [review]

**Pull request merged**
