### PR TITLE
docs: add dropdown options in the catalog

### PR DESCRIPTION
**Pull request by GurneeshBudhiraja**
Docs #2482

Add options to the dropdown in the catalog. 
Also, below is the screenshot of the change that has been made.

dropdown

- [X] I have read the [Contribution Guide](../packages/core/CONTRIBUTING.md) for this project.

### CODE REVIEW

**Comment by masabinhok** [comment]
I was assigned to this task, and it seems there’s been an overlap.

Could you please close your PR?

**Comment by GurneeshBudhiraja** [comment]
> I was assigned to this task, and it seems there’s been an overlap.
>
> Could you please close your PR?

@masabinhok Thanks for the comment. Since no PR had been raised by the assignee (you), I took the initiative to work on it and submit a PR. It is up to the maintainers to decide which PR they want to merge. Thanks!

**Review by rivka-ungar — APPROVED** [review]
Thanks @GurneeshBudhiraja!
Resolves #2482

**Comment by GurneeshBudhiraja** [comment]
@rivka-ungar glad have been of some help.

**Pull request merged**
