### PR TITLE
docs(Colors): migrate "Story of" to "Canvas of"

### LINKED ISSUE #2499: Convert the "Colors" docs page to not use `Story` component
Convert the "Colors" page to use Storybook's latest convention.
Storybook has deprecated the usage of `Story` component in mdx files.

There are 5 stories that should be migrated:
- Semantic colors
- Background colors
- Text colors
- Border colors
- Content colors

Example:
Instead of:
```typescript
<Canvas>
  <Story name="Semantic Colors">
    <SemanticColors />
  </Story>
</Canvas>
```

It should be something like:
```typescript
<Canvas of={ColorsStories.Semantic}>
```

**In our case, we also don't want to show the code for this story, so more specifically:**
```typescript
<Canvas of={ColorsStories.Semantic} sourceState="none">
```

This requires:
- Create a new file called `colors.stories.tsx` in the same folder where the `colors.stories.mdx` file is, in the format of [CSF](https://storybook.js.org/docs/api/csf).
	- It's content should be something like:
```typescript
const meta: Meta = {
  title: "Foundations/Colors"
};
export default meta;

type Story = StoryObj;

// this is one example, it should have a Story object for each of the above stated stories
export const Semantic: Story = {
  render: SemanticColors
};
```

- Change the file name of `colors.stories.mdx` to `Colors.mdx`
	- Its content should change according to the above `<Canvas />` example, 
	- `Meta` should, instead of having a "title" attr, have a "of" attr, with the value of `ColorsStories`. 
	(which is imported according to our convention as `import * as ColorsStories from "./colors.stories.tsx"`)

monday ticket:
https://monday.monday.com/boards/3532714909/pulses/6360059299

### PR DESCRIPTION
**Pull request by theDevSoham**
- [X] I have read the [Contribution Guide](../packages/core/CONTRIBUTING.md) for this project.

Resolves #2499

* Implemented `colors.stories.tsx` to follow [CSF 3.0](https://storybook.js.org/docs/api/csf)
* Changed `colors.stories.mdx` to `Colors.mdx`
* Updated `Meta` to use `of` attr instead of `title`

### CODE REVIEW

**Review by YossiSaadi — APPROVED** [review]
Excellent work! Thank you for contributing to Vibe! 🥇

**Comment by theDevSoham** [comment]
@YossiSaadi thanks a lot. Couldn't have done it without the detailed description of the issue! By the way, can I know when this issue will be closed and PR merged? Just asking

**Comment by YossiSaadi** [comment]
> @YossiSaadi thanks a lot. Couldn't have done it without the detailed description of the issue! By the way, can I know when this issue will be closed and PR merged? Just asking

was waiting for the CI to pass :) merging now

**Comment by theDevSoham** [comment]
> > @YossiSaadi thanks a lot. Couldn't have done it without the detailed description of the issue! By the way, can I know when this issue will be closed and PR merged? Just asking
> 
> was waiting for the CI to pass :) merging now

Thanks a lot :)

**Pull request merged**
