### PR TITLE
docs(Modal): migrate "Story of" to "Canvas of" in "Sizes" story

### LINKED ISSUE #2500: Convert a deprecated `Story` usage in Modal's docs page to use `Canvas`
Storybook has deprecated the usage of `Story` component in mdx files.
In Modal's story, we have:
```typescript
### Sizes

<Canvas>
  <Story of={ModalStories.WidthVariantsNormal} />
  <Story of={ModalStories.WidthVariantsFull} />
  <Story of={ModalStories.WidthVariantsCustom} />
</Canvas>
```

We need it to be instead:
```typescript
### Sizes

<Canvas of={ModalStories.Sizes} />
```

See `Button`'s story for ["Sizes"](https://github.com/mondaycom/vibe/blob/master/packages/core/src/components/Button/__stories__/Button.mdx#sizes)
And its appropriate [story source](https://github.com/mondaycom/vibe/blob/master/packages/core/src/components/Button/__stories__/Button.stories.tsx#L53)

monday ticket:
https://monday.monday.com/boards/3532714909/pulses/5661351160

### PR DESCRIPTION
**Pull request by aarifkhan7**
Migrated `<Story of={}>` (Deprecated) to `<Canvas of={}>` for Modal's story.

- [x] I have read the [Contribution Guide](../packages/core/CONTRIBUTING.md) for this project.

Resolves #2500

### CODE REVIEW

**Comment by aarifkhan7** [comment]
@YossiSaadi I have created a PR to resolve the issue. Please let me know if any changes are required! :)

**Review by YossiSaadi — COMMENTED** [review]
Awesome work here @aarifkhan7 !
Could you please run prettier on the file? the lint here fails

**Comment by aarifkhan7** [comment]
Thank you @YossiSaadi!
I have fixed the style issues.

**Review by YossiSaadi — APPROVED** [review]
Thanks for your first contribution to Vibe @aarifkhan7 ! We really appreciate it! 💯

**Pull request merged**
